// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("XPlot.D3")>]
[<assembly: AssemblyProductAttribute("XPlot")>]
[<assembly: AssemblyDescriptionAttribute("Data visualization library for F#")>]
[<assembly: AssemblyVersionAttribute("1.4.4")>]
[<assembly: AssemblyFileVersionAttribute("1.4.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "XPlot.D3"
    let [<Literal>] AssemblyProduct = "XPlot"
    let [<Literal>] AssemblyDescription = "Data visualization library for F#"
    let [<Literal>] AssemblyVersion = "1.4.4"
    let [<Literal>] AssemblyFileVersion = "1.4.4"
