// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("XPlot.D3")>]
[<assembly: AssemblyProductAttribute("XPlot")>]
[<assembly: AssemblyDescriptionAttribute("Data visualization library for F#")>]
[<assembly: AssemblyVersionAttribute("3.0.2")>]
[<assembly: AssemblyFileVersionAttribute("3.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "XPlot.D3"
    let [<Literal>] AssemblyProduct = "XPlot"
    let [<Literal>] AssemblyDescription = "Data visualization library for F#"
    let [<Literal>] AssemblyVersion = "3.0.2"
    let [<Literal>] AssemblyFileVersion = "3.0.2"
