// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("XPlot.GoogleCharts.Deedle")>]
[<assembly: AssemblyProductAttribute("XPlot")>]
[<assembly: AssemblyDescriptionAttribute("Data visualization library for F#")>]
[<assembly: AssemblyVersionAttribute("1.4.5")>]
[<assembly: AssemblyFileVersionAttribute("1.4.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "XPlot.GoogleCharts.Deedle"
    let [<Literal>] AssemblyProduct = "XPlot"
    let [<Literal>] AssemblyDescription = "Data visualization library for F#"
    let [<Literal>] AssemblyVersion = "1.4.5"
    let [<Literal>] AssemblyFileVersion = "1.4.5"
